### ISSUE TITLE
what should be there in classes.names folder?

### ISSUE THREAD

**Issue by manvirvirk** [woodsgao/pytorch_segmentation#2]

**Comment by WoodsGao** [comment]
A unique class name for each line.

**Comment by manvirvirk** [comment]
what is that class name? Could not get this point.

**Comment by manvirvirk** [comment]
I mean what should be the class name file format??

**Comment by woodsgao** [comment]
It's a text file. Here is the sample.

**Comment by WoodsGao** [comment]
It's a text file for marking indicators of each class during validating. Here is the sample for 3-classes condition.
```
class_1
class_2
class_3
```

**Comment by manvirvirk** [comment]
still i m getting this error:
PermissionError: [Errno 13] Permission denied: 'data/DRIVE\\classes.names'

Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nosave=opt.nosave or (opt.local_rank > 0),
  File "train.py", line 35, in train
    multi_scale=multi_scale)
  File "D:\pytorch_segmentation-master\utils\datasets.py", line 98, in __init__
    self.build_data()
  File "D:\pytorch_segmentation-master\utils\datasets.py", line 104, in build_data
    with open(osp.join(data_dir, 'classes.names'), 'r') as f:
PermissionError: [Errno 13] Permission denied: 'data/DRIVE\\classes.names'

**Comment by WoodsGao** [comment]
Well, please show the content of your `classes.names` file.
This may be caused by the lack of read and write permissions. Make sure you have read and write permissions for this file. If you do not have these permissions, use `chmod`.

**Comment by manvirvirk** [comment]
it contains class_1.txt file

**Comment by WoodsGao** [comment]
The classes.names is not a folder.
It's a **TEXT** file for marking indicators of each class during validating.

**Comment by manvirvirk** [comment]
![Capture](https://user-images.githubusercontent.com/54542400/79108324-bc3cff00-7d93-11ea-9494-4b5550f80715.PNG)
This is my database directory. Still i m facing issue:
 File "D:\pytorch_segmentation-master\utils\datasets.py", line 104, in build_data
    with open(osp.join(data_dir, 'classes.names'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/DRIVE\\classes.names'

**Comment by WoodsGao** [comment]
What is your command to run the program? Please give me sufficient information.

**Comment by manvirvirk** [comment]
python train.py --data data/DRIVE  This is my command to run training

**Comment by WoodsGao** [comment]
The **FULL** name of `classes.names` is `classes.names`!
You do not have a `classes.names`, What you have is `classes.names.txt`!
Please read the traceback carefully.
