### ISSUE TITLE
usage: split_dataset.py [-h] path split_dataset.py: error: the following arguments are required: path

### ISSUE THREAD

**Issue by manvirvirk** [woodsgao/pytorch_segmentation#3]
please help. Thanks

**Comment by WoodsGao** [comment]
Execte in this format: `python3 split_dataset.py <path-of-your-dataset>`
It will generate train.txt and valid.txt based on the images in the data folder

**Comment by manvirvirk** [comment]
PermissionError: [Errno 13] Permission denied: 'data/DRIVE\\classes.names'
i m getting this error when running train.py. 
Please help. What entries to be made in classes,.names folder??
